# Generated by Django 4.2.7 on 2025-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_achievement_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['rank']},
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trading_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('TRADING', 'Trading'), ('PORTFOLIO', 'Portfolio'), ('SOCIAL', 'Social'), ('LEARNING', 'Learning'), ('STREAK', 'Streak'), ('MILESTONE', 'Milestone')], max_length=9),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_xp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('ACHIEVEMENT', 'Achievement'), ('MILESTONE', 'Milestone'), ('SPECIAL', 'Special'), ('SEASONAL', 'Seasonal')], max_length=11),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='leaderboard_type',
            field=models.CharField(choices=[('XP', 'Experience Points'), ('PROFIT', 'Total Profit'), ('TRADES', 'Trade Count'), ('WIN_RATE', 'Win Rate'), ('VOLUME', 'Trading Volume')], max_length=8),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
